###
GET http://localhost:3000/

###
POST http://localhost:3000/register/
Content-Type: application/json

{
  "email": "zishan1@gmail.com",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}

###
POST http://localhost:3000/login/
Content-Type: application/json

{
  "email":"zishan@gmail.com",
  "password":"richard_567"
}

###
GET http://localhost:4000/user/tweets/feed/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjkxMjMwMTI0fQ.WP8Loq3an3L9XFF0aA8Zl0xxTJsE9K8Gl_r6vwh2HPY 


###
GET http://localhost:4000/user/following/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjkxMjMwMTI0fQ.WP8Loq3an3L9XFF0aA8Zl0xxTJsE9K8Gl_r6vwh2HPY 


###
GET http://localhost:4000/user/followers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjkxMjMwMTI0fQ.WP8Loq3an3L9XFF0aA8Zl0xxTJsE9K8Gl_r6vwh2HPY 

###
GET http://localhost:3000/tweets/2/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Inppc2hhbkBnbWFpbC5jb20iLCJpYXQiOjE3MTMwMzAyNDh9.gCXf7V_A6zbgqhhmQwDUfrL6OeheBOeULKXdnMrGr6c 


###
GET http://localhost:4000/tweets/2/likes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjkxMjMwMTI0fQ.WP8Loq3an3L9XFF0aA8Zl0xxTJsE9K8Gl_r6vwh2HPY 


###
GET http://localhost:4000/tweets/1/replies/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjkxMjMwMTI0fQ.WP8Loq3an3L9XFF0aA8Zl0xxTJsE9K8Gl_r6vwh2HPY 


###
GET http://localhost:4000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjkxMjMwMTI0fQ.WP8Loq3an3L9XFF0aA8Zl0xxTJsE9K8Gl_r6vwh2HPY 


###
POST http://localhost:4000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjkxMjMwMTI0fQ.WP8Loq3an3L9XFF0aA8Zl0xxTJsE9K8Gl_r6vwh2HPY 
Content-Type: application/json

{
   "tweet": "The Mornings..."
}

###
DELETE http://localhost:4000/tweets/19/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjkxMjMwMTI0fQ.WP8Loq3an3L9XFF0aA8Zl0xxTJsE9K8Gl_r6vwh2HPY 
